server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/os-storage-postgres
    driverClassName: org.postgresql.Driver
    username: os-storage-postgres
    password: os-storage-postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddlAuto: create
