server:
  port: 8761

spring:
  application:
    name: os-shop-eureka

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
