spring:
  datasource:
    url: jdbc:postgresql://pg:5432/studs
    driverClassName: org.postgresql.Driver
    username:
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddlAuto: update

  data:
    rest:
      default-media-type: application/xml
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        one-indexed-parameters: true

springdoc:
  version: 0.0.1
  default-consumes-media-type: application/xml
  default-produces-media-type: application/xml
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    supported-submit-methods: [ ]
    disable-swagger-default-url: true
