server:
  port: 8081
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: ../../ssl/online-shop.com.p12
    key-store-password: 123465
    key-alias: online-shop.com

spring:
  application:
    name: os-shop-service

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        one-indexed-parameters: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
# todo delete

springdoc:
  version: 0.0.1
  default-consumes-media-type: application/xml
  default-produces-media-type: application/xml
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    supported-submit-methods: [ ]
    disable-swagger-default-url: true

config:
  storage-api-base-url: https://localhost:8080/api/v1
