server:
  port: 8060
  ssl:
    key-store-type: PKCS12
    key-store: ../../../ssl/online-shop.com.p12
    key-store-password: 123465
    key-alias: online-shop.com

spring:
  application:
    name: os-shop-zuul

eureka:
  instance:
    prefer-ip-address: true

zuul:
  routes:
    os-shop-service:
      path: /**
      serviceId: os-shop-service
