server:
  address: ${STORAGE_SERVICE_HOST:localhost}
  port: ${STORAGE_SERVICE_PORT:8080}
  ssl:
    key-store-type: PKCS12
    key-store: ${SSL_P12_PATH:../../ssl/online-shop.com.p12}
    key-store-password: ${SSL_P12_PASSWORD:123465}
    key-alias: ${SSL_DOMAIN:online-shop.com}

spring:
  datasource:
    url: jdbc:postgresql://${STORAGE_POSTGRES_HOST:localhost}:${STORAGE_POSTGRES_PORT:5432}/${STORAGE_POSTGRES_DATABASE:os-storage-postgres}
    driverClassName: org.postgresql.Driver
    username: ${STORAGE_POSTGRES_USERNAME:os-storage-postgres}
    password: ${STORAGE_POSTGRES_PASSWORD:os-storage-postgres}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddlAuto: update

  data:
    rest:
      default-media-type: application/xml
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        one-indexed-parameters: true

springdoc:
  version: 0.0.1
  default-consumes-media-type: application/xml
  default-produces-media-type: application/xml
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    supported-submit-methods: [ ]
    disable-swagger-default-url: true
