version: "3.9"

services:
  os-storage-postgres:
    container_name: ${STORAGE_POSTGRES_NAME}
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: ${STORAGE_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${STORAGE_POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${STORAGE_POSTGRES_DATABASE}
    ports:
      - "${STORAGE_POSTGRES_PORT}:5432"
    networks:
      - os-storage-network

  os-storage-service:
    container_name: ${STORAGE_SERVICE_NAME}
    build:
      context: services
      dockerfile: storage/Dockerfile
    environment:
      STORAGE_SERVICE_HOST: ${STORAGE_SERVICE_HOST}
      STORAGE_SERVICE_PORT: ${STORAGE_SERVICE_PORT}
      STORAGE_POSTGRES_HOST: ${STORAGE_POSTGRES_NAME}
      STORAGE_POSTGRES_PORT: ${STORAGE_POSTGRES_PORT}
      STORAGE_POSTGRES_USERNAME: ${STORAGE_POSTGRES_USERNAME}
      STORAGE_POSTGRES_PASSWORD: ${STORAGE_POSTGRES_PASSWORD}
      STORAGE_POSTGRES_DATABASE: ${STORAGE_POSTGRES_DATABASE}
      SSL_P12_PATH: ${SSL_P12_PATH}
      SSL_P12_PASSWORD: ${SSL_P12_PASSWORD}
      SSL_DOMAIN: ${SSL_DOMAIN}
    depends_on:
      - os-storage-postgres
    ports:
      - "${STORAGE_SERVICE_PORT}:${STORAGE_SERVICE_PORT}"
    networks:
      - os-storage-network
      - os-shop-network
      - os-frontend-network
    volumes:
      - ${SSL_HOST_PATH}:${SSL_CONTAINER_PATH}

  os-shop-service:
    container_name: ${SHOP_SERVICE_NAME}
    build:
      context: services
      dockerfile: shop/Dockerfile
    environment:
      SHOP_SERVICE_HOST: ${SHOP_SERVICE_HOST}
      SHOP_SERVICE_PORT: ${SHOP_SERVICE_PORT}
      SHOP_STORAGE_API_BASE_URL: ${SHOP_STORAGE_API_BASE_URL}
      SSL_P12_PATH: ${SSL_P12_PATH}
      SSL_P12_PASSWORD: ${SSL_P12_PASSWORD}
      SSL_DOMAIN: ${SSL_DOMAIN}
    ports:
      - "${SHOP_SERVICE_PORT}:${SHOP_SERVICE_PORT}"
    networks:
      - os-shop-network
      - os-frontend-network
    volumes:
      - ${SSL_HOST_PATH}:${SSL_CONTAINER_PATH}

  os-frontend:
    container_name: ${FRONTEND_NAME}
    build:
      context: frontend
      args:
        REACT_APP_STORAGE_API_URL: ${FRONTEND_STORAGE_API_BASE_URL}
        REACT_APP_SHOP_API_URL: ${FRONTEND_SHOP_API_BASE_URL}
    environment:
      SSL_DOMAIN: ${SSL_DOMAIN}
      SSL_CRT_PATH: ${SSL_CRT_PATH}
      SSL_KEY_PATH: ${SSL_KEY_PATH}
    ports:
      - "${FRONTEND_PORT}:443"
    networks:
      - os-frontend-network
    volumes:
      - ${SSL_HOST_PATH}:${SSL_CONTAINER_PATH}

networks:
  os-storage-network:
    driver: bridge
  os-shop-network:
    driver: bridge
  os-frontend-network:
    external: true
